### ISSUE TITLE
rerender components after branch init is complete

### ISSUE THREAD

**Issue by fantapop** [flockcover/gatsby-plugin-branch-web-sdk#2]
I just recently integrated branch into a gatsby project.  I had bit of a tough time setting it up so that my components that relied on using the branch sdk were rerendered after the init was completed.  Redux would have worked but that would have added a lot of complexity to the small site so I ended up having a top level component call the init and then pass down a boolean value to any children which relied on branch to rerender them.

I just ran across your plugin and I'm wondering if this was a problem for you and how you solved it.

**Comment by apolishch** [comment]
We did not experience this problem as the Server Side Rendering just injects the branch object onto the window. Then we simply use this global branch object where it is needed.

**Comment by apolishch** [comment]
Going to go ahead and close this @fantapop Feel free to reopen if necessary
